name: Daily Puzzle Advance

on:
  schedule:
    - cron: '0 8 * * *'  # 12:00 AM Pacific (8:00 AM UTC)
  workflow_dispatch:  # Allows manual trigger

jobs:
  advance-puzzle:
    runs-on: ubuntu-latest
    steps:
      - name: Advance daily puzzle
        run: |
          curl -s -w "\nHTTP_STATUS:%{http_code}" \
            --max-time 30 \
            -X POST "${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}/functions/v1/frisc-daily-puzzle" \
            -H "Authorization: Bearer ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}" \
            -H "Content-Type: application/json"